# Generated by Django 6.0.3 on 2026-03-04 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('ddos', 'DDoS'), ('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('ransomware', 'Ransomware'), ('insider_threat', 'Insider Threat')], max_length=50)),
                ('severity', models.IntegerField()),
                ('impact_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_system', models.CharField(blank=True, max_length=100)),
                ('affected_assets', models.TextField(blank=True)),
                ('indicators', models.TextField(blank=True)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('predicted_type', models.CharField(blank=True, max_length=50)),
                ('prediction_confidence', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
